version: '3'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=bgp_database
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
  www:
    build: .
    volumes:
      - "./website:/var/www/html"
    ports:
      - 80:80
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
